---
- name: Windows Patching
  hosts: windows
  gather_facts: no

  tasks:
    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: installed
        reboot: yes
      register: update_result

    - name: Show update results
      debug:
        var: update_result
